# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install build dependencies if necessary
RUN apk add --no-cache build-base

# Install project dependencies using pip
RUN pip install --upgrade pip \
    && pip install .

# Expose the MCP server via stdio (default entrypoint)
CMD ["python", "get-uuid.py"]
